// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package storedb

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (owner_user_id, text, visibility)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, text, visibility
`

type CreateTaskParams struct {
	OwnerUserID string
	Text        string
	Visibility  string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.OwnerUserID, arg.Text, arg.Visibility)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Text,
		&i.Visibility,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT id, owner_user_id, text, visibility
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Text,
		&i.Visibility,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, owner_user_id, text, visibility
FROM tasks
ORDER BY text ASC, id ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Text,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
